# Generated by Django 6.0.3 on 2026-04-22 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_admin_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Notification',
                'verbose_name_plural': 'Order Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
